# Generated by Django 3.2.16 on 2023-02-06 15:37

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CappedEnrollmentLearnerCreditAccessPolicy',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('group_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('catalog_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('subsidy_uuid', models.UUIDField(db_index=True)),
                ('access_method', models.CharField(choices=[('direct', 'Direct'), ('request', 'Request'), ('assigned', 'Assigned')], db_index=True, default='direct', max_length=25)),
                ('spend_limit', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerLearnerEnrollmentCapLearnerCreditAccessPolicy',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('group_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('catalog_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('subsidy_uuid', models.UUIDField(db_index=True)),
                ('access_method', models.CharField(choices=[('direct', 'Direct'), ('request', 'Request'), ('assigned', 'Assigned')], db_index=True, default='direct', max_length=25)),
                ('per_learner_enrollment_limit', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerLearnerSpendCapLearnerCreditAccessPolicy',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('group_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('catalog_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('subsidy_uuid', models.UUIDField(db_index=True)),
                ('access_method', models.CharField(choices=[('direct', 'Direct'), ('request', 'Request'), ('assigned', 'Assigned')], db_index=True, default='direct', max_length=25)),
                ('per_learner_spend_limit', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAccessPolicy',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('group_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('catalog_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('subsidy_uuid', models.UUIDField(db_index=True)),
                ('access_method', models.CharField(choices=[('direct', 'Direct'), ('request', 'Request'), ('assigned', 'Assigned')], db_index=True, default='direct', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LicenseAccessPolicy',
            fields=[
                ('subscriptionaccesspolicy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subsidy_access_policy.subscriptionaccesspolicy')),
            ],
            options={
                'abstract': False,
            },
            bases=('subsidy_access_policy.subscriptionaccesspolicy',),
        ),
        migrations.CreateModel(
            name='LicenseRequestAccessPolicy',
            fields=[
                ('subscriptionaccesspolicy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subsidy_access_policy.subscriptionaccesspolicy')),
            ],
            options={
                'abstract': False,
            },
            bases=('subsidy_access_policy.subscriptionaccesspolicy',),
        ),
    ]
