# Generated by Django 3.2.16 on 2023-02-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CappedEnrollmentLearnerCreditAccessPolicy',
        ),
        migrations.DeleteModel(
            name='PerLearnerEnrollmentCapLearnerCreditAccessPolicy',
        ),
        migrations.DeleteModel(
            name='PerLearnerSpendCapLearnerCreditAccessPolicy',
        ),
        migrations.DeleteModel(
            name='LicenseAccessPolicy',
        ),
        migrations.DeleteModel(
            name='LicenseRequestAccessPolicy',
        ),
        migrations.DeleteModel(
            name='SubscriptionAccessPolicy',
        ),
    ]
