# Generated by Django 3.2.16 on 2023-02-17 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subsidy_access_policy', '0002_auto_20230216_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidyAccessPolicy',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('policy_type', models.CharField(max_length=64)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(help_text='Brief description about a specific policy.')),
                ('active', models.BooleanField(default=False)),
                ('group_uuid', models.UUIDField(db_index=True)),
                ('catalog_uuid', models.UUIDField(db_index=True)),
                ('subsidy_uuid', models.UUIDField(db_index=True)),
                ('access_method', models.CharField(choices=[('direct', 'Direct'), ('request', 'Request'), ('assigned', 'Assigned')], default='direct', max_length=32)),
                ('per_learner_enrollment_limit', models.IntegerField(blank=True, default=0, null=True)),
                ('per_learner_spend_limit', models.IntegerField(blank=True, default=0, null=True)),
                ('spend_limit', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalSubsidyAccessPolicy',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('policy_type', models.CharField(max_length=64)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('description', models.TextField(help_text='Brief description about a specific policy.')),
                ('active', models.BooleanField(default=False)),
                ('group_uuid', models.UUIDField(db_index=True)),
                ('catalog_uuid', models.UUIDField(db_index=True)),
                ('subsidy_uuid', models.UUIDField(db_index=True)),
                ('access_method', models.CharField(choices=[('direct', 'Direct'), ('request', 'Request'), ('assigned', 'Assigned')], default='direct', max_length=32)),
                ('per_learner_enrollment_limit', models.IntegerField(blank=True, default=0, null=True)),
                ('per_learner_spend_limit', models.IntegerField(blank=True, default=0, null=True)),
                ('spend_limit', models.IntegerField(blank=True, default=0, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical subsidy access policy',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CappedEnrollmentLearnerCreditAccessPolicy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subsidy_access_policy.subsidyaccesspolicy',),
        ),
        migrations.CreateModel(
            name='PerLearnerEnrollmentCreditAccessPolicy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subsidy_access_policy.subsidyaccesspolicy',),
        ),
        migrations.CreateModel(
            name='PerLearnerSpendCreditAccessPolicy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subsidy_access_policy.subsidyaccesspolicy',),
        ),
        migrations.CreateModel(
            name='SubscriptionAccessPolicy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subsidy_access_policy.subsidyaccesspolicy',),
        ),
    ]
