# Generated by Django 3.2.16 on 2023-03-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0004_auto_20230221_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubsidyaccesspolicy',
            name='enterprise_customer_uuid',
            field=models.UUIDField(db_index=True, help_text="The owning Enterprise Customer's UUID.  Cannot be blank or null.", null=True),
        ),
        migrations.AddField(
            model_name='subsidyaccesspolicy',
            name='enterprise_customer_uuid',
            field=models.UUIDField(db_index=True, help_text="The owning Enterprise Customer's UUID.  Cannot be blank or null.", null=True),
        ),
    ]
