# Generated by Django 3.2.16 on 2023-03-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0005_add_customer_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='group_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='Optional, currently useless field for future Enterprise Groups implementation.', null=True),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='group_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='Optional, currently useless field for future Enterprise Groups implementation.', null=True),
        ),
    ]
