# Generated by Django 3.2.18 on 2023-04-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0006_group_uuid_optional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CappedEnrollmentLearnerCreditAccessPolicy',
        ),
        migrations.DeleteModel(
            name='SubscriptionAccessPolicy',
        ),
    ]
