# Generated by Django 3.2.18 on 2023-04-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0007_remove_unused_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='per_learner_enrollment_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='per_learner_spend_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='spend_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='per_learner_enrollment_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='per_learner_spend_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='spend_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
