# Generated by Django 3.2.18 on 2023-05-04 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0008_default_limits_none'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='access_method',
            field=models.CharField(choices=[('direct', 'Direct'), ('request', 'Request'), ('assigned', 'Assigned')], default='direct', help_text='The mechanism by which learners access content in this policy, defaults to "direct".', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='active',
            field=models.BooleanField(default=False, help_text='Whether this policy is active, defaults to false.'),
        ),
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='catalog_uuid',
            field=models.UUIDField(db_index=True, help_text='The primary identifier of the catalog associated with this policy.'),
        ),
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='enterprise_customer_uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('00000000-0000-0000-0000-000000000000'), help_text="The owning Enterprise Customer's UUID.  Cannot be blank or null."),
        ),
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='per_learner_enrollment_limit',
            field=models.IntegerField(blank=True, default=None, help_text='The maximum number of enrollments allowed for a single learner under this policy. Defaults to null, which means that no such maximum exists.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='per_learner_spend_limit',
            field=models.IntegerField(blank=True, default=None, help_text='The maximum amount of allowed money spent for a single learner under this policy. Denoted in USD cents. Defaults to null, which means that no such maximum exists.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='policy_type',
            field=models.CharField(editable=False, help_text='The type of this policy (e.g. the name of an access policy proxy model).', max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='spend_limit',
            field=models.IntegerField(blank=True, default=None, help_text='The maximum number of allowed dollars to be spent, in aggregate, by all learners under this policy. Denoted in USD cents. Defaults to null, which means that no such maximum exists.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='subsidy_uuid',
            field=models.UUIDField(db_index=True, help_text='The primary identifier of the subsidy associated with this policy.'),
        ),
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='The uuid that uniquely identifies this policy record.'),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='access_method',
            field=models.CharField(choices=[('direct', 'Direct'), ('request', 'Request'), ('assigned', 'Assigned')], default='direct', help_text='The mechanism by which learners access content in this policy, defaults to "direct".', max_length=32),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='active',
            field=models.BooleanField(default=False, help_text='Whether this policy is active, defaults to false.'),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='catalog_uuid',
            field=models.UUIDField(db_index=True, help_text='The primary identifier of the catalog associated with this policy.'),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='enterprise_customer_uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('00000000-0000-0000-0000-000000000000'), help_text="The owning Enterprise Customer's UUID.  Cannot be blank or null."),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='per_learner_enrollment_limit',
            field=models.IntegerField(blank=True, default=None, help_text='The maximum number of enrollments allowed for a single learner under this policy. Defaults to null, which means that no such maximum exists.', null=True),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='per_learner_spend_limit',
            field=models.IntegerField(blank=True, default=None, help_text='The maximum amount of allowed money spent for a single learner under this policy. Denoted in USD cents. Defaults to null, which means that no such maximum exists.', null=True),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='policy_type',
            field=models.CharField(editable=False, help_text='The type of this policy (e.g. the name of an access policy proxy model).', max_length=64),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='spend_limit',
            field=models.IntegerField(blank=True, default=None, help_text='The maximum number of allowed dollars to be spent, in aggregate, by all learners under this policy. Denoted in USD cents. Defaults to null, which means that no such maximum exists.', null=True),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='subsidy_uuid',
            field=models.UUIDField(db_index=True, help_text='The primary identifier of the subsidy associated with this policy.'),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The uuid that uniquely identifies this policy record.', primary_key=True, serialize=False, unique=True),
        ),
    ]
