# Generated by Django 3.2.19 on 2023-06-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0010_verbose_policy_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='per_learner_enrollment_limit',
            field=models.IntegerField(blank=True, default=None, help_text='The maximum number of enrollments allowed for a single learner under this policy. Null value means no limit is set, which disables this feature. Required if policy_type = "PerLearnerEnrollmentCreditAccessPolicy".', null=True, verbose_name='Per-learner enrollment limit'),
        ),
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='per_learner_spend_limit',
            field=models.IntegerField(blank=True, default=None, help_text='The maximum amount of allowed money spent for a single learner under this policy. Denoted in USD cents. Null value means no limit is set, which disables this feature. Required if policy_type = "PerLearnerSpendCreditAccessPolicy".', null=True, verbose_name='Per-learner spend limit (USD cents)'),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='per_learner_enrollment_limit',
            field=models.IntegerField(blank=True, default=None, help_text='The maximum number of enrollments allowed for a single learner under this policy. Null value means no limit is set, which disables this feature. Required if policy_type = "PerLearnerEnrollmentCreditAccessPolicy".', null=True, verbose_name='Per-learner enrollment limit'),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='per_learner_spend_limit',
            field=models.IntegerField(blank=True, default=None, help_text='The maximum amount of allowed money spent for a single learner under this policy. Denoted in USD cents. Null value means no limit is set, which disables this feature. Required if policy_type = "PerLearnerSpendCreditAccessPolicy".', null=True, verbose_name='Per-learner spend limit (USD cents)'),
        ),
    ]
