# Generated by Django 3.2.19 on 2023-06-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0011_update_policy_field_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubsidyaccesspolicy',
            name='group_uuid',
        ),
        migrations.RemoveField(
            model_name='subsidyaccesspolicy',
            name='group_uuid',
        ),
    ]
