# Generated by Django 3.2.19 on 2023-07-12 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0012_remove_group_uuid_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPerLearnerEnrollmentCreditAccessPolicy',
            fields=[
            ],
            options={
                'verbose_name': 'historical per learner enrollment credit access policy',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subsidy_access_policy.historicalsubsidyaccesspolicy',),
        ),
        migrations.CreateModel(
            name='HistoricalPerLearnerSpendCreditAccessPolicy',
            fields=[
            ],
            options={
                'verbose_name': 'historical per learner spend credit access policy',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subsidy_access_policy.historicalsubsidyaccesspolicy',),
        ),
    ]
