# Generated by Django 3.2.20 on 2023-08-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0013_policy_proxy_models_history_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubsidyaccesspolicy',
            name='display_name',
            field=models.CharField(blank=True, default=None, help_text='User-facing display name for this policy record', max_length=512, null=True, verbose_name='Display name'),
        ),
        migrations.AddField(
            model_name='subsidyaccesspolicy',
            name='display_name',
            field=models.CharField(blank=True, default=None, help_text='User-facing display name for this policy record', max_length=512, null=True, verbose_name='Display name'),
        ),
    ]
