# Generated by Django 3.2.20 on 2023-08-28 13:25

from django.db import migrations
import enterprise_access.apps.subsidy_access_policy.models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0014_add_policy_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedLearnerCreditAccessPolicy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(enterprise_access.apps.subsidy_access_policy.models.CreditPolicyMixin, 'subsidy_access_policy.subsidyaccesspolicy'),
        ),
        migrations.CreateModel(
            name='HistoricalAssignedLearnerCreditAccessPolicy',
            fields=[
            ],
            options={
                'verbose_name': 'historical assigned learner credit access policy',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subsidy_access_policy.historicalsubsidyaccesspolicy',),
        ),
    ]
