# Generated by Django 3.2.20 on 2023-09-11 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0002_add_assignment_configuration_model'),
        ('subsidy_access_policy', '0015_assigned_learner_credit_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubsidyaccesspolicy',
            name='assignment_configuration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content_assignments.assignmentconfiguration'),
        ),
        migrations.AddField(
            model_name='subsidyaccesspolicy',
            name='assignment_configuration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidy_access_policy', to='content_assignments.assignmentconfiguration'),
        ),
    ]
