# Generated by Django 3.2.20 on 2023-09-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0003_drop_assignment_policy'),
        ('subsidy_access_policy', '0016_assignment_config_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsidyaccesspolicy',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='subsidyaccesspolicy',
            unique_together={('active', 'assignment_configuration')},
        ),
    ]
