# Generated by Django 3.2.21 on 2023-11-01 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0010_alter_learnercontentassignmentaction_assignment'),
        ('subsidy_access_policy', '0017_active_assignment_config_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='assignment_configuration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidy_access_policy', to='content_assignments.assignmentconfiguration'),
        ),
    ]
