# Generated by Django 4.2.6 on 2023-12-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0018_alter_subsidyaccesspolicy_assignment_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Brief description about a specific policy.'),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Brief description about a specific policy.'),
        ),
    ]
