# Generated by Django 4.2.8 on 2023-12-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0019_subsidyaccesspolicy_description_allow_blank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalassignedlearnercreditaccesspolicy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical assigned learner credit access policy', 'verbose_name_plural': 'historical assigned learner credit access policys'},
        ),
        migrations.AlterModelOptions(
            name='historicalperlearnerenrollmentcreditaccesspolicy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical per learner enrollment credit access policy', 'verbose_name_plural': 'historical per learner enrollment credit access policys'},
        ),
        migrations.AlterModelOptions(
            name='historicalperlearnerspendcreditaccesspolicy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical per learner spend credit access policy', 'verbose_name_plural': 'historical per learner spend credit access policys'},
        ),
        migrations.AlterModelOptions(
            name='historicalsubsidyaccesspolicy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical subsidy access policy', 'verbose_name_plural': 'historical subsidy access policys'},
        ),
    ]
