# Generated by Django 4.2.9 on 2024-01-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0020_alter_historicalassignedlearnercreditaccesspolicy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubsidyaccesspolicy',
            name='retired',
            field=models.BooleanField(default=False, help_text="True means redeemability of content using this policy has been enabled. Set this to False to deactivate the policy but keep it visible from an admin's perspective (useful when you want to just expire a policy without expiring the whole plan)."),
        ),
        migrations.AddField(
            model_name='subsidyaccesspolicy',
            name='retired',
            field=models.BooleanField(default=False, help_text="True means redeemability of content using this policy has been enabled. Set this to False to deactivate the policy but keep it visible from an admin's perspective (useful when you want to just expire a policy without expiring the whole plan)."),
        ),
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='active',
            field=models.BooleanField(default=False, help_text='Set to FALSE to deactivate and hide this policy. Use this when you want to disable redemption and make it disappear from all frontends, effectively soft-deleting it. Default is False (deactivated).'),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='active',
            field=models.BooleanField(default=False, help_text='Set to FALSE to deactivate and hide this policy. Use this when you want to disable redemption and make it disappear from all frontends, effectively soft-deleting it. Default is False (deactivated).'),
        ),
    ]
