# Generated by Django 4.2.10 on 2024-02-15 21:00

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0021_subsidyaccesspolicy_retired'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyGroupAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('enterprise_group_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The uuid that uniquely identifies the associated group.', unique=True)),
                ('subsidy_access_policy', models.ForeignKey(help_text='The SubsidyAccessPolicy that this group is tied to.', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='subsidy_access_policy.subsidyaccesspolicy')),
            ],
            options={
                'unique_together': {('subsidy_access_policy', 'enterprise_group_uuid')},
            },
        ),
    ]
