# Generated by Django 4.2.10 on 2024-03-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0022_policygroupassociation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policygroupassociation',
            name='enterprise_group_uuid',
            field=models.UUIDField(blank=True, help_text='The uuid that uniquely identifies the associated group.', null=True),
        ),
    ]
