# Generated by Django 4.2.9 on 2024-03-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0023_alter_policygroupassociation_enterprise_group_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubsidyaccesspolicy',
            name='late_redemption_allowed_until',
            field=models.DateTimeField(blank=True, help_text='Before this date, "late redemptions" will be allowed. If empty, late redemptions are disallowed.', null=True),
        ),
        migrations.AddField(
            model_name='subsidyaccesspolicy',
            name='late_redemption_allowed_until',
            field=models.DateTimeField(blank=True, help_text='Before this date, "late redemptions" will be allowed. If empty, late redemptions are disallowed.', null=True),
        ),
    ]
