# Generated by Django 4.2.11 on 2024-04-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0025_forced_policy_redemption_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcedpolicyredemption',
            name='transaction_uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, help_text=('The transaction uuid caused by successful redemption.',), null=True),
        ),
        migrations.AlterField(
            model_name='historicalforcedpolicyredemption',
            name='transaction_uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, help_text=('The transaction uuid caused by successful redemption.',), null=True),
        ),
    ]
