# Generated by Django 4.2.13 on 2024-06-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0026_forced_redemption_tx_blank_not_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubsidyaccesspolicy',
            name='retired_at',
            field=models.DateTimeField(blank=True, help_text='The date and time when this Subsidy is considered retired.', null=True),
        ),
        migrations.AddField(
            model_name='subsidyaccesspolicy',
            name='retired_at',
            field=models.DateTimeField(blank=True, help_text='The date and time when this Subsidy is considered retired.', null=True),
        ),
    ]
