# Generated by Django 4.2.20 on 2025-03-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0028_alter_historicalsubsidyaccesspolicy_retired_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubsidyaccesspolicy',
            name='browse_and_request',
            field=models.BooleanField(default=False, help_text='If selected, it means browse and request is active on this policy.'),
        ),
        migrations.AddField(
            model_name='subsidyaccesspolicy',
            name='browse_and_request',
            field=models.BooleanField(default=False, help_text='If selected, it means browse and request is active on this policy.'),
        ),
    ]
