# Generated by Django 3.2.11 on 2022-02-07 18:25

from django.db import migrations, models

from enterprise_access.apps.subsidy_request.constants import SubsidyRequestStates

def update_subsidy_request_states(apps, schema_editor):
    LicenseRequest = apps.get_model('subsidy_request', 'LicenseRequest')
    CouponCodeRequest = apps.get_model('subsidy_request', 'CouponCodeRequest')

    state_mappings = {
        'pending_review': SubsidyRequestStates.REQUESTED,
        'approved_pending': SubsidyRequestStates.PENDING,
        'approved_fulfilled': SubsidyRequestStates.APPROVED,
        'denied': SubsidyRequestStates.DECLINED
    }

    for old_state in state_mappings:
        new_state = state_mappings[old_state]
        LicenseRequest.objects.filter(state=old_state).update(state=new_state)
        CouponCodeRequest.objects.filter(state=old_state).update(state=new_state)

def revert_subsidy_request_states(apps, schema_editor):
    LicenseRequest = apps.get_model('subsidy_request', 'LicenseRequest')
    CouponCodeRequest = apps.get_model('subsidy_request', 'CouponCodeRequest')

    state_mappings = {
        SubsidyRequestStates.REQUESTED: 'pending_review',
        SubsidyRequestStates.PENDING: 'approved_pending',
        SubsidyRequestStates.APPROVED: 'approved_fulfilled',
        SubsidyRequestStates.DECLINED: 'denied'
    }

    for new_state in state_mappings:
        old_state = state_mappings[new_state]
        LicenseRequest.objects.filter(state=new_state).update(state=old_state)
        CouponCodeRequest.objects.filter(state=new_state).update(state=old_state)

class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_request', '0003_make_requests_soft_deletable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcoderequest',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error')], default='requested', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalcouponcoderequest',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error')], default='requested', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicallicenserequest',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error')], default='requested', max_length=25),
        ),
        migrations.AlterField(
            model_name='licenserequest',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error')], default='requested', max_length=25),
        ),
        migrations.RunPython(update_subsidy_request_states, revert_subsidy_request_states),
    ]
