# Generated by Django 3.2.11 on 2022-02-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_request', '0004_update_subsidy_states'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponcoderequest',
            old_name='denial_reason',
            new_name='decline_reason',
        ),
        migrations.RenameField(
            model_name='historicalcouponcoderequest',
            old_name='denial_reason',
            new_name='decline_reason',
        ),
        migrations.RenameField(
            model_name='historicallicenserequest',
            old_name='denial_reason',
            new_name='decline_reason',
        ),
        migrations.RenameField(
            model_name='licenserequest',
            old_name='denial_reason',
            new_name='decline_reason',
        ),
    ]
