# Generated by Django 3.2.11 on 2022-03-02 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subsidy_request', '0005_auto_20220211_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcoderequest',
            name='lms_user_id',
        ),
        migrations.RemoveField(
            model_name='couponcoderequest',
            name='reviewer_lms_user_id',
        ),
        migrations.RemoveField(
            model_name='historicalcouponcoderequest',
            name='lms_user_id',
        ),
        migrations.RemoveField(
            model_name='historicalcouponcoderequest',
            name='reviewer_lms_user_id',
        ),
        migrations.RemoveField(
            model_name='historicallicenserequest',
            name='lms_user_id',
        ),
        migrations.RemoveField(
            model_name='historicallicenserequest',
            name='reviewer_lms_user_id',
        ),
        migrations.RemoveField(
            model_name='licenserequest',
            name='lms_user_id',
        ),
        migrations.RemoveField(
            model_name='licenserequest',
            name='reviewer_lms_user_id',
        ),
        migrations.AddField(
            model_name='couponcoderequest',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_subsidy_request_couponcoderequest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couponcoderequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_request_couponcoderequest', to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcouponcoderequest',
            name='reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcouponcoderequest',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallicenserequest',
            name='reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallicenserequest',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_subsidy_request_licenserequest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subsidy_request_licenserequest', to='core.user'),
            preserve_default=False,
        ),
    ]
