# Generated by Django 3.2.11 on 2022-02-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_request', '0005_auto_20220211_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcoderequest',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcouponcoderequest',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicallicenserequest',
            name='user_email',
            field=models.EmailField(default='some@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='user_email',
            field=models.EmailField(default='someemail@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
