# Generated by Django 3.2.11 on 2022-03-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_request', '0006_auto_20220302_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcoderequest',
            name='course_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='historicalcouponcoderequest',
            name='course_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='historicallicenserequest',
            name='course_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='course_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
