# Generated by Django 3.2.12 on 2022-03-30 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subsidy_request', '0009_lowercase_subsidy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcoderequest',
            name='coupon_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='couponcoderequest',
            name='enterprise_customer_uuid',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='couponcoderequest',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error')], db_index=True, default='requested', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalcouponcoderequest',
            name='coupon_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcouponcoderequest',
            name='enterprise_customer_uuid',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcouponcoderequest',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error')], db_index=True, default='requested', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicallicenserequest',
            name='enterprise_customer_uuid',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallicenserequest',
            name='license_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallicenserequest',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error')], db_index=True, default='requested', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicallicenserequest',
            name='subscription_plan_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenserequest',
            name='enterprise_customer_uuid',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='licenserequest',
            name='license_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenserequest',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error')], db_index=True, default='requested', max_length=25),
        ),
        migrations.AlterField(
            model_name='licenserequest',
            name='subscription_plan_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterIndexTogether(
            name='couponcoderequest',
            index_together={('uuid', 'state'), ('user', 'enterprise_customer_uuid', 'state', 'course_id')},
        ),
        migrations.AlterIndexTogether(
            name='licenserequest',
            index_together={('uuid', 'state'), ('user', 'enterprise_customer_uuid', 'state', 'course_id')},
        ),
    ]
