# Generated by Django 3.2.13 on 2022-04-26 11:45

import collections
from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_request', '0010_subsidy_request_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcoderequest',
            name='course_partners',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'indent': 4, 'separators': (',', ':')}, help_text='List of course partner dictionaries.', load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True),
        ),
        migrations.AddField(
            model_name='historicalcouponcoderequest',
            name='course_partners',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'indent': 4, 'separators': (',', ':')}, help_text='List of course partner dictionaries.', load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True),
        ),
        migrations.AddField(
            model_name='historicallicenserequest',
            name='course_partners',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'indent': 4, 'separators': (',', ':')}, help_text='List of course partner dictionaries.', load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True),
        ),
        migrations.AddField(
            model_name='licenserequest',
            name='course_partners',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'indent': 4, 'separators': (',', ':')}, help_text='List of course partner dictionaries.', load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True),
        ),
    ]
