# Generated by Django 4.2.8 on 2023-12-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_request', '0012_alter_couponcoderequest_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcouponcoderequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical coupon code request', 'verbose_name_plural': 'historical coupon code requests'},
        ),
        migrations.AlterModelOptions(
            name='historicallicenserequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical license request', 'verbose_name_plural': 'historical license requests'},
        ),
        migrations.AlterModelOptions(
            name='historicalsubsidyrequestcustomerconfiguration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical subsidy request customer configuration', 'verbose_name_plural': 'historical subsidy request customer configurations'},
        ),
    ]
