# Generated by Django 4.2.20 on 2025-04-13 18:33

import collections
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.encoder
import jsonfield.fields
import model_utils.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_assignments', '0023_historicallearnercontentassignment_is_assigned_course_run_and_more'),
        ('subsidy_request', '0013_alter_historicalcouponcoderequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerCreditRequestConfiguration',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(db_index=True, default=False, help_text='Whether this configuration is active. Defaults to True.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='couponcoderequest',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('reversed', 'Reversed')], db_index=True, default='requested', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalcouponcoderequest',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('reversed', 'Reversed')], db_index=True, default='requested', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicallicenserequest',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('reversed', 'Reversed')], db_index=True, default='requested', max_length=25),
        ),
        migrations.AlterField(
            model_name='licenserequest',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('reversed', 'Reversed')], db_index=True, default='requested', max_length=25),
        ),
        migrations.CreateModel(
            name='LearnerCreditRequest',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course_id', models.CharField(blank=True, max_length=128, null=True)),
                ('course_title', models.CharField(blank=True, max_length=255, null=True)),
                ('course_partners', jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'indent': 4, 'separators': (',', ':')}, help_text='List of course partner dictionaries.', load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True)),
                ('enterprise_customer_uuid', models.UUIDField(db_index=True)),
                ('state', models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('reversed', 'Reversed')], db_index=True, default='requested', max_length=25)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('assignment', models.OneToOneField(blank=True, help_text='The content assignment associated with this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_request', to='content_assignments.learnercontentassignment')),
                ('learner_credit_request_config', models.ForeignKey(blank=True, help_text='The learner credit request configuration associated with this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_credit_requests', to='subsidy_request.learnercreditrequestconfiguration')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalLearnerCreditRequestConfiguration',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('active', models.BooleanField(db_index=True, default=False, help_text='Whether this configuration is active. Defaults to True.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical learner credit request configuration',
                'verbose_name_plural': 'historical learner credit request configurations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLearnerCreditRequest',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('course_id', models.CharField(blank=True, max_length=128, null=True)),
                ('course_title', models.CharField(blank=True, max_length=255, null=True)),
                ('course_partners', jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'indent': 4, 'separators': (',', ':')}, help_text='List of course partner dictionaries.', load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True)),
                ('enterprise_customer_uuid', models.UUIDField(db_index=True)),
                ('state', models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('reversed', 'Reversed')], db_index=True, default='requested', max_length=25)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assignment', models.ForeignKey(blank=True, db_constraint=False, help_text='The content assignment associated with this request.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content_assignments.learnercontentassignment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('learner_credit_request_config', models.ForeignKey(blank=True, db_constraint=False, help_text='The learner credit request configuration associated with this request.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subsidy_request.learnercreditrequestconfiguration')),
                ('reviewer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical learner credit request',
                'verbose_name_plural': 'historical learner credit requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='learnercreditrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['requested', 'pending'])), fields=('user', 'enterprise_customer_uuid', 'course_id'), name='unique_learner_course_request'),
        ),
    ]
