# Generated by Django 4.2.21 on 2025-06-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_request', '0014_learnercreditrequestconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallearnercreditrequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course price in USD.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='learnercreditrequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course price in USD.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsubsidyrequestcustomerconfiguration',
            name='subsidy_type',
            field=models.CharField(blank=True, choices=[('license', 'License Subsidy'), ('coupon', 'Coupon Subsidy'), ('learner_credit', 'Learner Credit Subsidy')], help_text='Which type of subsidy is used to grant access.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='subsidyrequestcustomerconfiguration',
            name='subsidy_type',
            field=models.CharField(blank=True, choices=[('license', 'License Subsidy'), ('coupon', 'Coupon Subsidy'), ('learner_credit', 'Learner Credit Subsidy')], help_text='Which type of subsidy is used to grant access.', max_length=32, null=True),
        ),
    ]
