# Generated by Django 4.2.21 on 2025-05-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_request', '0014_learnercreditrequestconfiguration_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='couponcoderequest',
            new_name='subsidy_req_uuid_8c5efe_idx',
            old_fields=('uuid', 'state'),
        ),
        migrations.RenameIndex(
            model_name='couponcoderequest',
            new_name='subsidy_req_user_id_4e7462_idx',
            old_fields=('user', 'enterprise_customer_uuid', 'state', 'course_id'),
        ),
        migrations.RenameIndex(
            model_name='licenserequest',
            new_name='subsidy_req_uuid_e19871_idx',
            old_fields=('uuid', 'state'),
        ),
        migrations.RenameIndex(
            model_name='licenserequest',
            new_name='subsidy_req_user_id_ea0637_idx',
            old_fields=('user', 'enterprise_customer_uuid', 'state', 'course_id'),
        ),
        migrations.AlterField(
            model_name='historicalsubsidyrequestcustomerconfiguration',
            name='subsidy_type',
            field=models.CharField(blank=True, choices=[('license', 'License Subsidy'), ('coupon', 'Coupon Subsidy'), ('learner_credit', 'Learner Credit Subsidy')], help_text='Which type of subsidy is used to grant access.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='subsidyrequestcustomerconfiguration',
            name='subsidy_type',
            field=models.CharField(blank=True, choices=[('license', 'License Subsidy'), ('coupon', 'Coupon Subsidy'), ('learner_credit', 'Learner Credit Subsidy')], help_text='Which type of subsidy is used to grant access.', max_length=32, null=True),
        ),
    ]
