# Generated by Django 4.2.21 on 2025-06-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_request', '0015_alter_historicalsubsidyrequestcustomerconfiguration_subsidy_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='learnercreditrequest',
            name='unique_learner_course_request',
        ),
        migrations.AddConstraint(
            model_name='learnercreditrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['requested', 'approved', 'error', 'accepted'])), fields=('user', 'enterprise_customer_uuid', 'course_id'), name='unique_learner_course_request'),
        ),
    ]
