# Generated by Django 4.2.21 on 2025-06-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_request', '0015_historicallearnercreditrequest_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallearnercreditrequest',
            name='amount',
            field=models.BigIntegerField(blank=True, help_text='Cost of the content in USD Cents.', null=True),
        ),
        migrations.AlterField(
            model_name='learnercreditrequest',
            name='amount',
            field=models.BigIntegerField(blank=True, help_text='Cost of the content in USD Cents.', null=True),
        ),
    ]
