# Generated by Django 4.2.21 on 2025-06-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_request', '0016_remove_learnercreditrequest_unique_learner_course_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallearnercreditrequest',
            name='course_price',
            field=models.BigIntegerField(blank=True, help_text='Cost of the content in USD Cents.', null=True),
        ),
        migrations.AddField(
            model_name='learnercreditrequest',
            name='course_price',
            field=models.BigIntegerField(blank=True, help_text='Cost of the content in USD Cents.', null=True),
        ),
    ]
