# Generated by Django 4.2.21 on 2025-06-16 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subsidy_request', '0017_historicallearnercreditrequest_course_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerCreditRequestActions',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recent_action', models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('reversed', 'Reversed'), ('reminded', 'Reminded')], db_index=True, help_text='The type of action taken on the learner credit request.', max_length=25)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('reminded', 'Waiting For Learner'), ('approved', 'Waiting For Learner'), ('accepted', 'Redeemed By Learner'), ('declined', 'Declined'), ('reversed', 'Refunded'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, help_text='The message shown to the user about the request status.', max_length=25)),
                ('error_reason', models.CharField(blank=True, choices=[('failed_approval', 'Failed: Approval'), ('failed_decline', 'Failed: Decline'), ('failed_cancellation', 'Failed: Cancellation')], db_index=True, help_text='The type of error that occurred during the action, if any.', max_length=255, null=True)),
                ('traceback', models.TextField(blank=True, editable=False, help_text='Any traceback we recorded when an error was encountered.', null=True)),
                ('learner_credit_request', models.ForeignKey(help_text='The learner credit request associated with this action.', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='subsidy_request.learnercreditrequest')),
            ],
            options={
                'verbose_name': 'Learner Credit Request Action',
                'verbose_name_plural': 'Learner Credit Request Actions',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLearnerCreditRequestActions',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('recent_action', models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('error', 'Error'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('reversed', 'Reversed'), ('reminded', 'Reminded')], db_index=True, help_text='The type of action taken on the learner credit request.', max_length=25)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('reminded', 'Waiting For Learner'), ('approved', 'Waiting For Learner'), ('accepted', 'Redeemed By Learner'), ('declined', 'Declined'), ('reversed', 'Refunded'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, help_text='The message shown to the user about the request status.', max_length=25)),
                ('error_reason', models.CharField(blank=True, choices=[('failed_approval', 'Failed: Approval'), ('failed_decline', 'Failed: Decline'), ('failed_cancellation', 'Failed: Cancellation')], db_index=True, help_text='The type of error that occurred during the action, if any.', max_length=255, null=True)),
                ('traceback', models.TextField(blank=True, editable=False, help_text='Any traceback we recorded when an error was encountered.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('learner_credit_request', models.ForeignKey(blank=True, db_constraint=False, help_text='The learner credit request associated with this action.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='subsidy_request.learnercreditrequest')),
            ],
            options={
                'verbose_name': 'historical Learner Credit Request Action',
                'verbose_name_plural': 'historical Learner Credit Request Actions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
