# Generated by Django 5.2 on 2025-06-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_request', '0018_learnercreditrequestactions_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='couponcoderequest',
            new_name='subsidy_req_uuid_8c5efe_idx',
            old_fields=('uuid', 'state'),
        ),
        migrations.RenameIndex(
            model_name='couponcoderequest',
            new_name='subsidy_req_user_id_4e7462_idx',
            old_fields=('user', 'enterprise_customer_uuid', 'state', 'course_id'),
        ),
        migrations.RenameIndex(
            model_name='licenserequest',
            new_name='subsidy_req_uuid_e19871_idx',
            old_fields=('uuid', 'state'),
        ),
        migrations.RenameIndex(
            model_name='licenserequest',
            new_name='subsidy_req_user_id_ea0637_idx',
            old_fields=('user', 'enterprise_customer_uuid', 'state', 'course_id'),
        ),
    ]
