# Generated by Django 4.2.21 on 2025-08-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_request', '0020_alter_historicallearnercreditrequestactions_error_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallearnercreditrequestactions',
            name='error_reason',
            field=models.CharField(blank=True, choices=[('failed_approval', 'Failed: Approval'), ('failed_decline', 'Failed: Decline'), ('failed_cancellation', 'Failed: Cancellation'), ('failed_redemption', 'Failed: Redemption'), ('failed_reversal', 'Failed: Reversal'), ('email_error', 'Email error')], db_index=True, help_text='The type of error that occurred during the action, if any.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='learnercreditrequestactions',
            name='error_reason',
            field=models.CharField(blank=True, choices=[('failed_approval', 'Failed: Approval'), ('failed_decline', 'Failed: Decline'), ('failed_cancellation', 'Failed: Cancellation'), ('failed_redemption', 'Failed: Redemption'), ('failed_reversal', 'Failed: Reversal'), ('email_error', 'Email error')], db_index=True, help_text='The type of error that occurred during the action, if any.', max_length=255, null=True),
        ),
    ]
