# Generated by Django 3.2.11 on 2022-03-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_request', '0007_auto_20220309_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubsidyrequestcustomerconfiguration',
            name='last_remind_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsidyrequestcustomerconfiguration',
            name='last_remind_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
