# Generated by Django 4.2.16 on 2024-10-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '0014_alter_process_parent_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultEnterpriseCourseEnrollmentProcess',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('viewflow.process',),
        ),
    ]
