# Generated by Django 4.2.21 on 2025-06-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0004_sub_plan_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerProvisionSubscriptionTrialCustomerWorkflow',
            fields=[
            ],
            options={
                'verbose_name': 'Trigger Subscription Trial Provisioning Workflow',
                'verbose_name_plural': 'Trigger Subscription Trial Provisioning Workflows',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('provisioning.provisionnewcustomerworkflow',),
        ),
    ]
