# Generated by Django 4.2.24 on 2025-11-05 22:57

from django.db import migrations, models
import django.utils.timezone
import enterprise_access.apps.provisioning.models
import jsonfield.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0005_triggerprovisionsubscriptiontrialcustomerworkflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetCreateFirstPaidSubscriptionPlanStep',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('input_data', jsonfield.fields.JSONField(blank=True, default=None)),
                ('output_data', jsonfield.fields.JSONField(blank=True, default=None, null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('exception_message', models.TextField(blank=True, null=True)),
                ('workflow_record_uuid', models.UUIDField(help_text='UUID of the workflow record')),
                ('preceding_step_uuid', models.UUIDField(help_text='UUID of the preceding workflow step record, if any', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(enterprise_access.apps.provisioning.models.CheckoutIntentStepMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GetCreateSubscriptionPlanRenewalStep',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('input_data', jsonfield.fields.JSONField(blank=True, default=None)),
                ('output_data', jsonfield.fields.JSONField(blank=True, default=None, null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('exception_message', models.TextField(blank=True, null=True)),
                ('workflow_record_uuid', models.UUIDField(help_text='UUID of the workflow record')),
                ('preceding_step_uuid', models.UUIDField(help_text='UUID of the preceding workflow step record, if any', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(enterprise_access.apps.provisioning.models.CheckoutIntentStepMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NotificationStep',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('input_data', jsonfield.fields.JSONField(blank=True, default=None)),
                ('output_data', jsonfield.fields.JSONField(blank=True, default=None, null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('exception_message', models.TextField(blank=True, null=True)),
                ('workflow_record_uuid', models.UUIDField(help_text='UUID of the workflow record')),
                ('preceding_step_uuid', models.UUIDField(help_text='UUID of the preceding workflow step record, if any', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(enterprise_access.apps.provisioning.models.CheckoutIntentStepMixin, models.Model),
        ),
        migrations.RenameModel(
            old_name='GetCreateSubscriptionPlanStep',
            new_name='GetCreateTrialSubscriptionPlanStep',
        ),
    ]
