# Generated by Django 4.2.17 on 2025-01-24 14:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddToppingsStep',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('input_data', jsonfield.fields.JSONField(blank=True)),
                ('output_data', jsonfield.fields.JSONField(blank=True, editable=False, null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PizzaPipeline',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('input_data', jsonfield.fields.JSONField(blank=True)),
                ('output_data', jsonfield.fields.JSONField(blank=True, editable=False, null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StretchDoughStep',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('input_data', jsonfield.fields.JSONField(blank=True)),
                ('output_data', jsonfield.fields.JSONField(blank=True, editable=False, null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('pipeline_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.pizzapipeline')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BakePizzaStep',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('input_data', jsonfield.fields.JSONField(blank=True)),
                ('output_data', jsonfield.fields.JSONField(blank=True, editable=False, null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('pipeline_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.pizzapipeline')),
                ('preceding_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.addtoppingsstep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='addtoppingsstep',
            name='pipeline_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.pizzapipeline'),
        ),
        migrations.AddField(
            model_name='addtoppingsstep',
            name='preceding_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.stretchdoughstep'),
        ),
    ]
