# Generated by Django 4.2.17 on 2025-01-27 15:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtoppingsstep',
            name='output_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bakepizzastep',
            name='output_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pizzapipeline',
            name='output_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stretchdoughstep',
            name='output_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
