# Generated by Django 3.2.11 on 2022-01-18 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields

from enterprise_access.apps.core import constants

def create_roles(apps, schema_editor):
    """
    Create the enterprise subscriptions roles if they do not already exist.
    """
    EnterpriseAccessFeatureRole = apps.get_model('core', 'EnterpriseAccessFeatureRole')
    EnterpriseAccessFeatureRole.objects.update_or_create(name=constants.REQUESTS_ADMIN_ROLE)
    EnterpriseAccessFeatureRole.objects.update_or_create(name=constants.REQUESTS_LEARNER_ROLE)


def delete_roles(apps, schema_editor):
    """
    Delete the enterprise subscriptions roles.
    """
    EnterpriseAccessFeatureRole = apps.get_model('core', 'EnterpriseAccessFeatureRole')
    EnterpriseAccessFeatureRole.objects.filter(name=constants.REQUESTS_ADMIN_ROLE).delete()
    EnterpriseAccessFeatureRole.objects.filter(name=constants.REQUESTS_LEARNER_ROLE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseAccessFeatureRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnterpriseAccessRoleAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('applies_to_all_contexts', models.BooleanField(default=False, help_text='If true, indicates that the user is effectively assigned their role for any and all contexts. Defaults to False.')),
                ('enterprise_customer_uuid', models.UUIDField(blank=True, null=True, verbose_name='Enterprise Customer UUID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enterpriseaccessfeaturerole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_roles, delete_roles),
    ]
