# Generated by Django 3.2.11 on 2022-01-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enterprise_access_feature_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lms_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
