# Generated by Django 4.2.19 on 2025-03-03 21:48

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testworkflowstep',
            name='workflow_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.testworkflow'),
        ),
        migrations.AlterField(
            model_name='testworkflow',
            name='input_data',
            field=jsonfield.fields.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='testworkflow',
            name='output_data',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='testworkflowstep',
            name='input_data',
            field=jsonfield.fields.JSONField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='testworkflowstep',
            name='output_data',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
    ]
