# Generated by Django 4.2.21 on 2025-08-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0002_checkout_intent_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalenterpriseslugreservation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalenterpriseslugreservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='EnterpriseSlugReservation',
        ),
        migrations.DeleteModel(
            name='HistoricalEnterpriseSlugReservation',
        ),
    ]
