# Generated by Django 4.2.21 on 2025-08-22 14:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0003_drop_slug_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutintent',
            name='country',
            field=django_countries.fields.CountryField(help_text="The customer's country", max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicalcheckoutintent',
            name='country',
            field=django_countries.fields.CountryField(help_text="The customer's country", max_length=2, null=True),
        ),
    ]
