# Generated by Django 4.2.24 on 2025-09-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0004_checkout_intent_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutintent',
            name='terms_metadata',
            field=models.JSONField(blank=True, help_text='Metadata relating to the terms and conditions accepted by the user.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcheckoutintent',
            name='terms_metadata',
            field=models.JSONField(blank=True, help_text='Metadata relating to the terms and conditions accepted by the user.', null=True),
        ),
    ]
