# Generated by Django 4.2.24 on 2025-09-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0005_add_terms_metadata_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutintent',
            name='enterprise_uuid',
            field=models.UUIDField(blank=True, help_text='The uuid of the EnterpriseCustomer, once successfully provisioned', null=True),
        ),
        migrations.AddField(
            model_name='checkoutintent',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='The Stripe Customer identifier associated with this record', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcheckoutintent',
            name='enterprise_uuid',
            field=models.UUIDField(blank=True, help_text='The uuid of the EnterpriseCustomer, once successfully provisioned', null=True),
        ),
        migrations.AddField(
            model_name='historicalcheckoutintent',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='The Stripe Customer identifier associated with this record', max_length=255, null=True),
        ),
    ]
