# Generated by Django 4.2.24 on 2025-10-02 00:58

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0006_customer_uuid_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutintent',
            name='enterprise_name',
            field=models.CharField(blank=True, help_text='Checkout intent enterprise customer name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutintent',
            name='enterprise_slug',
            field=models.SlugField(blank=True, help_text='Checkout intent enterprise customer slug', max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='historicalcheckoutintent',
            name='enterprise_name',
            field=models.CharField(blank=True, help_text='Checkout intent enterprise customer name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcheckoutintent',
            name='enterprise_slug',
            field=models.SlugField(blank=True, help_text='Checkout intent enterprise customer slug', max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
