# Generated by Django 4.2.24 on 2025-10-03 15:22

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0007_checkoutintent_enterprise_name_slug_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEventData',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('event_id', models.CharField(help_text='The unique event identifier', max_length=255, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text='The stripe event type.', max_length=255)),
                ('data', models.JSONField(default={}, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='The event payload data')),
                ('checkout_intent', models.ForeignKey(help_text='The related CheckoutIntent, which is infered from the stripe customer id.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_billing.checkoutintent')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
