# Generated by Django 4.2.25 on 2025-10-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0008_stripe_event_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutintent',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('errored_stripe_checkout', 'Errored (Stripe Checkout)'), ('errored_provisioning', 'Errored (Provisioning)'), ('errored_fulfillment_stalled', 'Errored (Fulfillment Stalled)'), ('errored_backoffice', 'Errored (Backoffice)'), ('expired', 'Expired')], default='created', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcheckoutintent',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('errored_stripe_checkout', 'Errored (Stripe Checkout)'), ('errored_provisioning', 'Errored (Provisioning)'), ('errored_fulfillment_stalled', 'Errored (Fulfillment Stalled)'), ('errored_backoffice', 'Errored (Backoffice)'), ('expired', 'Expired')], default='created', max_length=255),
        ),
    ]
