# Generated by Django 4.2.25 on 2025-10-20 19:30

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0008_stripe_event_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEventSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('event_id', models.CharField(db_index=True, help_text='The unique Stripe event identifier', max_length=255)),
                ('event_type', models.CharField(db_index=True, help_text='The Stripe event type', max_length=255)),
                ('subscription_plan_uuid', models.UUIDField(blank=True, db_index=True, help_text='UUID of the SubscriptionPlan from License Manager', null=True)),
                ('stripe_object_type', models.CharField(blank=True, db_index=True, help_text='Type of the main Stripe object (invoice, subscription, etc.)', max_length=50, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, help_text='Stripe subscription ID extracted from event data', max_length=255, null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, db_index=True, help_text='Stripe invoice ID extracted from event data', max_length=255, null=True)),
                ('subscription_status', models.CharField(blank=True, help_text='Status of the Stripe subscription (active, canceled, etc.)', max_length=50, null=True)),
                ('subscription_period_start', models.DateTimeField(blank=True, help_text='Start date of the subscription period', null=True)),
                ('subscription_period_end', models.DateTimeField(blank=True, help_text='End date of the subscription period', null=True)),
                ('invoice_amount_paid', models.IntegerField(blank=True, help_text='Amount paid on the invoice in cents', null=True)),
                ('invoice_unit_amount', models.IntegerField(blank=True, help_text='Unit amount from the primary invoice line item as integer cents', null=True)),
                ('invoice_unit_amount_decimal', models.DecimalField(blank=True, decimal_places=12, help_text='Unit amount from the primary invoice line item in decimal cents', max_digits=20, null=True)),
                ('invoice_quantity', models.IntegerField(blank=True, help_text='Quantity from the primary invoice line item', null=True)),
                ('invoice_currency', models.CharField(blank=True, help_text='Currency of the invoice', max_length=3, null=True)),
                ('checkout_intent', models.ForeignKey(help_text='The related CheckoutIntent', null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_billing.checkoutintent')),
                ('stripe_event_data', models.OneToOneField(help_text='Reference to the original StripeEventData record', on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='customer_billing.stripeeventdata')),
            ],
            options={
                'verbose_name': 'Stripe Event Summary',
                'verbose_name_plural': 'Stripe Event Summaries',
                'db_table': 'customer_billing_stripe_event_summary',
                'indexes': [models.Index(fields=['subscription_plan_uuid'], name='customer_bi_subscri_5be4bf_idx'), models.Index(fields=['stripe_subscription_id'], name='customer_bi_stripe__32d371_idx'), models.Index(fields=['stripe_invoice_id'], name='customer_bi_stripe__3ae7d7_idx'), models.Index(fields=['event_type', 'checkout_intent'], name='customer_bi_event_t_4533d5_idx'), models.Index(fields=['stripe_object_type'], name='customer_bi_stripe__6a6d45_idx')],
            },
        ),
    ]
