# Generated by Django 4.2.25 on 2025-10-22 11:32

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0009_stripe_event_summary_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeeventdata',
            name='data',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='The event payload data'),
        ),
    ]
