# Generated by Django 4.2.25 on 2025-10-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0010_alter_stripeeventdata_data'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stripeeventsummary',
            name='customer_bi_subscri_5be4bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='stripeeventsummary',
            name='customer_bi_stripe__32d371_idx',
        ),
        migrations.RemoveIndex(
            model_name='stripeeventsummary',
            name='customer_bi_stripe__3ae7d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='stripeeventsummary',
            name='customer_bi_event_t_4533d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='stripeeventsummary',
            name='customer_bi_stripe__6a6d45_idx',
        ),
    ]
