# Generated by Django 4.2.25 on 2025-10-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0011_drop_superfluous_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='checkoutintent',
            name='customer_bi_state_50f734_idx',
        ),
        migrations.RemoveIndex(
            model_name='checkoutintent',
            name='customer_bi_enterpr_19a87f_idx',
        ),
        migrations.RemoveIndex(
            model_name='checkoutintent',
            name='customer_bi_enterpr_1eb230_idx',
        ),
        migrations.RemoveIndex(
            model_name='checkoutintent',
            name='customer_bi_expires_97774f_idx',
        ),
        migrations.RemoveIndex(
            model_name='checkoutintent',
            name='customer_bi_stripe__1e3320_idx',
        ),
        migrations.AlterField(
            model_name='checkoutintent',
            name='enterprise_name',
            field=models.CharField(blank=True, db_index=True, help_text='Checkout intent enterprise customer name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutintent',
            name='enterprise_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='The uuid of the EnterpriseCustomer, once successfully provisioned', null=True),
        ),
        migrations.AlterField(
            model_name='checkoutintent',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('errored_stripe_checkout', 'Errored (Stripe Checkout)'), ('errored_provisioning', 'Errored (Provisioning)'), ('expired', 'Expired')], db_index=True, default='created', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcheckoutintent',
            name='enterprise_name',
            field=models.CharField(blank=True, db_index=True, help_text='Checkout intent enterprise customer name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcheckoutintent',
            name='enterprise_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='The uuid of the EnterpriseCustomer, once successfully provisioned', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcheckoutintent',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('errored_stripe_checkout', 'Errored (Stripe Checkout)'), ('errored_provisioning', 'Errored (Provisioning)'), ('expired', 'Expired')], db_index=True, default='created', max_length=255),
        ),
        migrations.AddIndex(
            model_name='stripeeventsummary',
            index=models.Index(fields=['event_type', 'checkout_intent'], name='customer_bi_event_t_4533d5_idx'),
        ),
    ]
