# Generated by Django 4.2.25 on 2025-10-27 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0012_cleanup_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutintent',
            name='uuid',
            field=models.UUIDField(help_text='Unique identifier for this record, can be used for cross-service references', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalcheckoutintent',
            name='uuid',
            field=models.UUIDField(db_index=True, help_text='Unique identifier for this record, can be used for cross-service references', null=True),
        ),
    ]
