# Generated by Django 4.2.25 on 2025-10-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0014_populate_checkout_intent_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeeventsummary',
            name='stripe_event_created_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the Stripe event was created', null=True),
        ),
    ]
