# Generated by Django 4.2.25 on 2025-10-28 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0015_summary_stripe_created_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutintent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique identifier for this record, can be used for cross-service references', unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcheckoutintent',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique identifier for this record, can be used for cross-service references'),
        ),
    ]
