# Generated by Django 4.2.25 on 2025-10-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0016_alter_checkoutintent_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeeventsummary',
            name='future_subscription_plan_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID of the future SubscriptionPlan from License Manager', null=True),
        ),
        migrations.AddField(
            model_name='stripeeventsummary',
            name='subscription_plan_renewal_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID of the SubscriptionPlanRenewal from License Manager, it related the (current) plan to the future plan', null=True),
        ),
    ]
