# Generated by Django 4.2.24 on 2025-10-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0009_add_fulfillment_stalled_states'),
        ('customer_billing', '0016_alter_checkoutintent_uuid_and_more'),
    ]

    operations = [
    ]
