# Generated by Django 4.2.25 on 2025-10-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0016_alter_checkoutintent_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeeventsummary',
            name='upcoming_invoice_amount_due',
            field=models.IntegerField(blank=True, help_text='Upcoming invoice amount due related to this event/subscription', null=True),
        ),
    ]
