# Generated by Django 4.2.25 on 2025-11-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0017_summary_renewal_and_future_plan_uuids'),
        ('customer_billing', '0017_upcoming_invoice_amount_due'),
    ]

    operations = [
    ]
