# Generated by Django 4.2.25 on 2025-11-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0017_summary_renewal_and_future_plan_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutintent',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('errored_backoffice', 'Errored (Backoffice) - Salesforce integration failed during checkout intent update'), ('errored_fulfillment_stalled', 'Errored (Fulfillment Stalled) - Checkout intent stuck in paid state, fulfillment workflow may have failed'), ('errored_provisioning', 'Errored (Provisioning) - Enterprise provisioning workflow failed after payment'), ('expired', 'Expired')], db_index=True, default='created', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcheckoutintent',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('errored_backoffice', 'Errored (Backoffice) - Salesforce integration failed during checkout intent update'), ('errored_fulfillment_stalled', 'Errored (Fulfillment Stalled) - Checkout intent stuck in paid state, fulfillment workflow may have failed'), ('errored_provisioning', 'Errored (Provisioning) - Enterprise provisioning workflow failed after payment'), ('expired', 'Expired')], db_index=True, default='created', max_length=255),
        ),
    ]
