# Generated by Django 4.2.24 on 2025-10-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0017_merge_20251030_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutintent',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('errored_provisioning', 'Errored (Provisioning)'), ('errored_fulfillment_stalled', 'Errored (Fulfillment Stalled)'), ('errored_backoffice', 'Errored (Backoffice)'), ('expired', 'Expired')], db_index=True, default='created', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcheckoutintent',
            name='state',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('errored_provisioning', 'Errored (Provisioning)'), ('errored_fulfillment_stalled', 'Errored (Fulfillment Stalled)'), ('errored_backoffice', 'Errored (Backoffice)'), ('expired', 'Expired')], db_index=True, default='created', max_length=255),
        ),
    ]
