# Generated by Django 4.2.24 on 2025-11-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0019_stripeeventsummary_subscription_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeeventsummary',
            name='subscription_plan_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID of the Trial SubscriptionPlan from License Manager', null=True),
        ),
    ]
