# Generated by Django 4.2.25 on 2025-11-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0022_subs_renewal_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalselfservicesubscriptionrenewal',
            name='subscription_plan_renewal_id',
            field=models.IntegerField(help_text='UUID of the SubscriptionPlanRenewal in License Manager'),
        ),
        migrations.AlterField(
            model_name='selfservicesubscriptionrenewal',
            name='subscription_plan_renewal_id',
            field=models.IntegerField(help_text='UUID of the SubscriptionPlanRenewal in License Manager'),
        ),
    ]
