# Generated by Django 5.2.8 on 2025-11-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0023_renewal_id_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeeventsummary',
            name='future_subscription_plan_uuid',
        ),
        migrations.RemoveField(
            model_name='stripeeventsummary',
            name='subscription_plan_renewal_uuid',
        ),
    ]
