# Generated by Django 5.2.8 on 2025-11-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0024_drop_summary_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalselfservicesubscriptionrenewal',
            name='prior_subscription_plan_uuid',
            field=models.UUIDField(blank=True, help_text='The prior (or current) subscription plan uuid on this renewal', null=True),
        ),
        migrations.AddField(
            model_name='historicalselfservicesubscriptionrenewal',
            name='renewed_subscription_plan_uuid',
            field=models.UUIDField(blank=True, help_text='The renewed (or future) subscription plan uuid on this renewal', null=True),
        ),
        migrations.AddField(
            model_name='selfservicesubscriptionrenewal',
            name='prior_subscription_plan_uuid',
            field=models.UUIDField(blank=True, help_text='The prior (or current) subscription plan uuid on this renewal', null=True),
        ),
        migrations.AddField(
            model_name='selfservicesubscriptionrenewal',
            name='renewed_subscription_plan_uuid',
            field=models.UUIDField(blank=True, help_text='The renewed (or future) subscription plan uuid on this renewal', null=True),
        ),
    ]
