# Generated by Django 5.2.9 on 2025-12-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0025_add_renewal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeeventsummary',
            name='canceled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the subscription was cancelled, null if still active', null=True),
        ),
    ]
