# Generated by Django 5.2.9 on 2026-01-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0025_add_renewal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeeventsummary',
            name='subscription_cancel_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the subscription is scheduled to be canceled', null=True),
        ),
    ]
