# Generated by Django 3.2.20 on 2023-09-11 18:29

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentConfiguration',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='historicallearnercontentassignment',
            name='assignment_policy',
        ),
        migrations.RemoveField(
            model_name='learnercontentassignment',
            name='assignment_policy',
        ),
        migrations.AddField(
            model_name='historicallearnercontentassignment',
            name='assignment_configuration',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='AssignmentConfiguration defining the lifecycle rules of this assignment.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='content_assignments.assignmentconfiguration'),
        ),
        migrations.AddField(
            model_name='learnercontentassignment',
            name='assignment_configuration',
            field=models.ForeignKey(help_text='AssignmentConfiguration defining the lifecycle rules of this assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='content_assignments.assignmentconfiguration'),
        ),
    ]
