# Generated by Django 3.2.20 on 2023-09-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0002_add_assignment_configuration_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalassignmentpolicy',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalassignmentpolicy',
            name='subsidy_access_policy',
        ),
        migrations.DeleteModel(
            name='AssignmentPolicy',
        ),
        migrations.DeleteModel(
            name='HistoricalAssignmentPolicy',
        ),
    ]
