# Generated by Django 3.2.21 on 2023-09-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0005_assignment_configuration_add_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learnercontentassignment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='learnercontentassignment',
            unique_together={('assignment_configuration', 'learner_email', 'content_key'), ('assignment_configuration', 'lms_user_id', 'content_key')},
        ),
    ]
