# Generated by Django 3.2.21 on 2023-09-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0006_unique_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallearnercontentassignment',
            name='state',
            field=models.CharField(choices=[('allocated', 'Allocated'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('errored', 'Errored')], db_index=True, default='allocated', help_text="The current state of the LearnerContentAssignment. One of: ['allocated', 'accepted', 'cancelled', 'errored']", max_length=255),
        ),
        migrations.AlterField(
            model_name='learnercontentassignment',
            name='state',
            field=models.CharField(choices=[('allocated', 'Allocated'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('errored', 'Errored')], db_index=True, default='allocated', help_text="The current state of the LearnerContentAssignment. One of: ['allocated', 'accepted', 'cancelled', 'errored']", max_length=255),
        ),
    ]
