# Generated by Django 4.2.6 on 2023-10-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0008_assignment_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallearnercontentassignment',
            name='content_title',
            field=models.CharField(blank=True, help_text='The ContentMetadata.title from content corresponding to the content_key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learnercontentassignment',
            name='content_title',
            field=models.CharField(blank=True, help_text='The ContentMetadata.title from content corresponding to the content_key', max_length=255, null=True),
        ),
    ]
