# Generated by Django 3.2.21 on 2023-11-01 20:35

from django.db import migrations, models
import django.db.models.deletion


def delete_actions_without_assignment(apps, schema_editor):
    """
    Deletes Actions without Assignments. This is a workaround for a bug where at least one Assignment was deleted
    before the associated Actions were, resulting in Django Admin for Actions throwing an error.
    
    By running a data migration to delete the Actions without an associated Assignment, this error should be avoided.

    This issue will be prevented in the future by also setting `on_delete=CASCADE` such that when an Assignment is
    deleted, its associated Actions will be deleted as well.
    """
    LearnerContentAssignmentAction = apps.get_model('content_assignments', 'LearnerContentAssignmentAction')
    LearnerContentAssignmentAction.objects.filter(assignment__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0009_historicallearnercontentassignment_content_title_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_actions_without_assignment, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='learnercontentassignmentaction',
            name='assignment',
            field=models.ForeignKey(help_text='The LearnerContentAssignment on which this action was performed.', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='content_assignments.learnercontentassignment'),
        ),
    ]
