# Generated by Django 4.2.6 on 2023-11-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0011_alter_learnercontentassignmentaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallearnercontentassignmentaction',
            name='error_reason',
            field=models.CharField(blank=True, choices=[('cancel_error', 'Cancel error'), ('email_error', 'Email error'), ('internal_api_error', 'Internal API error'), ('remind_error', 'Remind error')], db_index=True, help_text='The type of error that occurred during the action, if any.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='learnercontentassignmentaction',
            name='error_reason',
            field=models.CharField(blank=True, choices=[('cancel_error', 'Cancel error'), ('email_error', 'Email error'), ('internal_api_error', 'Internal API error'), ('remind_error', 'Remind error')], db_index=True, help_text='The type of error that occurred during the action, if any.', max_length=255, null=True),
        ),
    ]
