# Generated by Django 4.2.6 on 2023-12-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0012_assignmentaction_add_automatic_cancellation_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallearnercontentassignment',
            name='has_dismissed',
            field=models.BooleanField(default=False, help_text='True if the learner dismissed alert for cancelled or expired assignments. Default to false'),
        ),
        migrations.AddField(
            model_name='learnercontentassignment',
            name='has_dismissed',
            field=models.BooleanField(default=False, help_text='True if the learner dismissed alert for cancelled or expired assignments. Default to false'),
        ),
    ]
