# Generated by Django 4.2.8 on 2023-12-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0013_add_redeemed_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalassignmentconfiguration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical assignment configuration', 'verbose_name_plural': 'historical assignment configurations'},
        ),
        migrations.AlterModelOptions(
            name='historicallearnercontentassignment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical learner content assignment', 'verbose_name_plural': 'historical learner content assignments'},
        ),
        migrations.AlterModelOptions(
            name='historicallearnercontentassignmentaction',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical learner content assignment action', 'verbose_name_plural': 'historical learner content assignment actions'},
        ),
    ]
