# Generated by Django 4.2.11 on 2024-04-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0018_alter_historicallearnercontentassignmentaction_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallearnercontentassignment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, help_text='The last time this assignment was reversed. Null means the assignment is not reversed.', null=True),
        ),
        migrations.AddField(
            model_name='learnercontentassignment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, help_text='The last time this assignment was reversed. Null means the assignment is not reversed.', null=True),
        ),
    ]
