# Generated by Django 4.2.11 on 2024-04-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0018_alter_historicallearnercontentassignmentaction_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallearnercontentassignment',
            name='preferred_course_run_key',
            field=models.CharField(blank=True, db_index=True, help_text='The preferred course run that the admin primarily intends for the learner, and the one used to control nudge emails. This is automatically set at assignment creation or re-allocation time.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learnercontentassignment',
            name='preferred_course_run_key',
            field=models.CharField(blank=True, db_index=True, help_text='The preferred course run that the admin primarily intends for the learner, and the one used to control nudge emails. This is automatically set at assignment creation or re-allocation time.', max_length=255, null=True),
        ),
    ]
