# Generated by Django 4.2.13 on 2024-06-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0019_learnercontentassignment_preferred_course_run_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallearnercontentassignment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, help_text='The last time this assignment was reversed. Null means the assignment is not currently reversed.', null=True),
        ),
        migrations.AddField(
            model_name='learnercontentassignment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, help_text='The last time this assignment was reversed. Null means the assignment is not currently reversed.', null=True),
        ),
        migrations.AlterField(
            model_name='historicallearnercontentassignment',
            name='state',
            field=models.CharField(choices=[('allocated', 'Allocated'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('errored', 'Errored'), ('expired', 'Expired'), ('reversed', 'Reversed')], db_index=True, default='allocated', help_text="The current state of the LearnerContentAssignment. One of: ['allocated', 'accepted', 'cancelled', 'errored', 'expired', 'reversed']", max_length=255),
        ),
        migrations.AlterField(
            model_name='historicallearnercontentassignmentaction',
            name='action_type',
            field=models.CharField(choices=[('learner_linked', 'Learner linked to customer'), ('notified', 'Learner notified of assignment'), ('reminded', 'Learner reminded about assignment'), ('redeemed', 'Learner redeemed the assigned content'), ('cancelled', 'Learner assignment cancelled'), ('cancelled_acknowledged', 'Learner assignment cancellation acknowledged by learner'), ('expired', 'Learner assignment expired'), ('expired_acknowledged', 'Learner assignment expiration acknowledged by learner'), ('reversed', 'Transaction for this assignment has been reversed')], db_index=True, help_text='The type of action take on the related assignment record.', max_length=255),
        ),
        migrations.AlterField(
            model_name='learnercontentassignment',
            name='state',
            field=models.CharField(choices=[('allocated', 'Allocated'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('errored', 'Errored'), ('expired', 'Expired'), ('reversed', 'Reversed')], db_index=True, default='allocated', help_text="The current state of the LearnerContentAssignment. One of: ['allocated', 'accepted', 'cancelled', 'errored', 'expired', 'reversed']", max_length=255),
        ),
        migrations.AlterField(
            model_name='learnercontentassignmentaction',
            name='action_type',
            field=models.CharField(choices=[('learner_linked', 'Learner linked to customer'), ('notified', 'Learner notified of assignment'), ('reminded', 'Learner reminded about assignment'), ('redeemed', 'Learner redeemed the assigned content'), ('cancelled', 'Learner assignment cancelled'), ('cancelled_acknowledged', 'Learner assignment cancellation acknowledged by learner'), ('expired', 'Learner assignment expired'), ('expired_acknowledged', 'Learner assignment expiration acknowledged by learner'), ('reversed', 'Transaction for this assignment has been reversed')], db_index=True, help_text='The type of action take on the related assignment record.', max_length=255),
        ),
    ]
