# Generated by Django 4.2.13 on 2024-07-10 14:13

import datetime

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0021_backfill_allocated_at'),
    ]

    # To keep history somewhat-sane, set the default for *historical* records
    # to datetime.min instead of datetime.now.
    # We've already backfilled allocated_at via 0021, so there should
    # be no nulls in those records.
    operations = [
        migrations.AlterField(
            model_name='historicallearnercontentassignment',
            name='allocated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), help_text='The last time the assignment was allocated. Cannot be null.'),
        ),
        migrations.AlterField(
            model_name='learnercontentassignment',
            name='allocated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The last time the assignment was allocated. Cannot be null.'),
        ),
    ]
