# Generated by Django 4.2.25 on 2025-11-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0024_mariadb_uuid_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallearnercontentassignment',
            name='admin_lms_user_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='The id of the Open edX Admin LMS user record. This may be null at time of creation.', null=True),
        ),
        migrations.AddField(
            model_name='learnercontentassignment',
            name='admin_lms_user_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='The id of the Open edX Admin LMS user record. This may be null at time of creation.', null=True),
        ),
    ]
