name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        django-version: ["pinned", "5.2"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install requirements
      run: make requirements
    - name: Upgrade packages
      run: |
        pip install -U pip wheel
        if [[ "${{ matrix.django-version }}" != "pinned" ]]; then
          pip install "django~=${{ matrix.django-version }}.0"
          pip check # fail if this test-reqs/Django combination is broken
        fi
    - name: Validate translations
      run: make validate_translations
    - name: Run tests
      run: make test
    # - name: Run lint  # 2025-09-23 AED: pylint is crashing in github CI
    #   run: make lint
    - name: Run style
      run: make style isort_check pii_check check_keywords
